### ISSUE TITLE
Variable Declaration

### ISSUE THREAD

**Issue by kunalait** [jinboszu/lb-lis#1]
I am executing your code, could you please explain the meaning of TC, S, T, N, Si, Ti input variables?

Thank you so much for consideration.

**Comment by jinboszu** [comment]
- TC: number of instances in the file
- For each instance:
  - S: number of stacks
  - T: number tiers (max height of stacks)
  - N: number of blocks
  - For each block:
    - Si: stack index of block i
    - Ti: tier index of block i

**Comment by kunalait** [comment]
Hi Jinboszu/Lb-Lis,

Thank you for your reply

I gave the input

TC number of instance 1
S number of stack 3
T number of tiers 4
N no of block 10
Si = 3
Ti = 4

I am getting segmentation fault. Kindly suggest me to resolve this issue.

Thanks & Regards
Kunal

**Comment by jinboszu** [comment]
If there are `N = 10` blocks in an instance, you should provide 10 `(Si, Ti)` pairs, each indicating the slot of block `i = 1, ..., N`.

Please refer to the data format of the files in the folder `input`.
